name = input("이름을 입력하세요: ")
student_id = input("학번을 입력하세요: ")
dept_id = input("학과를 입력하세요: ")
school_name = input("학교 이름을 입력하세요: ")

print()
print(f"이름: {name}")
print(f"학번: {student_id}")
print(f"학과: {dept_id}")
print(f"학교 이름: {school_name}")